services:
    mongo:
        image: mongo:6.0
        container_name: mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017
            - 28017:28017
            - 27018:27018
            - 27019:27019
        volumes:
            - mongo-data:/data/db
        networks:
            - services
            - apps

    mongo-express:
        image: mongo-express:1.0
        container_name: mongo-express
        restart: unless-stopped
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin123
        ports:
            - 8081:8081
        depends_on:
            - mongo
        networks:
            - services
            - apps


    authentik:
        image: authentik/authentik:latest
        container_name: authentik
        restart: unless-stopped
        environment:
            AUTHENTIK_SECRET_KEY: supersecretkey
            AUTHENTIK_POSTGRESQL_HOST: db
            AUTHENTIK_POSTGRESQL_PORT: 5432
            AUTHENTIK_POSTGRESQL_USER: authentik
            AUTHENTIK_POSTGRESQL_PASSWORD: example
            AUTHENTIK_POSTGRESQL_DATABASE: authentik
            AUTHENTIK_REDIS_HOST: redis
            AUTHENTIK_REDIS_PORT: 6379
            AUTHENTIK_SERVER_HOSTNAME: auth.example.com
            AUTHENTIK_EMAIL_HOST: smtp.example.com
            AUTHENTIK_EMAIL_PORT: 587
            AUTHENTIK_EMAIL_HOST_USER:

        networks:
          - services
          - apps

    redis:
        image: redis:7
        container_name: redis
        restart: unless-stopped
        ports:
            - 6379:6379
        networks:
            - services
            - apps

    postgres:
        image: postgres:15
        container_name: authentik-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: authentik
            POSTGRES_PASSWORD: example
            POSTGRES_DB: authentik
        volumes:
            - authentik-data:/var/lib/postgresql/data
        networks:
            - services
            - apps

volumes:
    mongo-data:

networks:
    services:
